services:
  delivery-app-server:
    build:
      context: .
    env_file:
      - ./.env
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - mongo

  nginx:
    image: nginx:stable-alpine
    ports:
      - "8000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - delivery-app-server

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db:
