services:
  delivery-app-server:
    build:
      context: .
    ports:
      - 8000:8000
    env_file:
      - ./.env
    volumes:
      - ./:/app:ro
      - /app/node_modules
    command: ["npm", "run", "dev"]
